/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UmbraBatchSendFactory } from "./UmbraBatchSendFactory";
export type { UmbraBatchSend } from "./UmbraBatchSend";
