/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UmbraBatchSendInterface extends ethers.utils.Interface {
  functions: {
    "approveToken(address)": FunctionFragment;
    "batchSend(uint256,tuple[],tuple[],tuple[])": FunctionFragment;
    "batchSendEth(uint256,tuple[])": FunctionFragment;
    "batchSendTokens(uint256,tuple[],tuple[])": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approveToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSend",
    values: [
      BigNumberish,
      {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      { amount: BigNumberish; tokenAddr: string }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSendEth",
    values: [
      BigNumberish,
      {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSendTokens",
    values: [
      BigNumberish,
      {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      { amount: BigNumberish; tokenAddr: string }[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchSend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSendEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSendTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "BatchSendExecuted(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchSendExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class UmbraBatchSend extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UmbraBatchSendInterface;

  functions: {
    approveToken(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approveToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    batchSend(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "batchSend(uint256,tuple[],tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    batchSendEth(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "batchSendEth(uint256,tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    batchSendTokens(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "batchSendTokens(uint256,tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  approveToken(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approveToken(address)"(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  batchSend(
    _tollCommitment: BigNumberish,
    _ethParams: {
      receiver: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    _tokenParams: {
      receiver: string;
      tokenAddr: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "batchSend(uint256,tuple[],tuple[],tuple[])"(
    _tollCommitment: BigNumberish,
    _ethParams: {
      receiver: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    _tokenParams: {
      receiver: string;
      tokenAddr: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  batchSendEth(
    _tollCommitment: BigNumberish,
    _params: {
      receiver: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "batchSendEth(uint256,tuple[])"(
    _tollCommitment: BigNumberish,
    _params: {
      receiver: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  batchSendTokens(
    _tollCommitment: BigNumberish,
    _params: {
      receiver: string;
      tokenAddr: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "batchSendTokens(uint256,tuple[],tuple[])"(
    _tollCommitment: BigNumberish,
    _params: {
      receiver: string;
      tokenAddr: string;
      amount: BigNumberish;
      pkx: BytesLike;
      ciphertext: BytesLike;
    }[],
    _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    approveToken(_token: string, overrides?: CallOverrides): Promise<void>;

    "approveToken(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    batchSend(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchSend(uint256,tuple[],tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchSendEth(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchSendEth(uint256,tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchSendTokens(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchSendTokens(uint256,tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BatchSendExecuted(sender: string | null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    approveToken(_token: string, overrides?: Overrides): Promise<BigNumber>;

    "approveToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    batchSend(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "batchSend(uint256,tuple[],tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    batchSendEth(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "batchSendEth(uint256,tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    batchSendTokens(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "batchSendTokens(uint256,tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveToken(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approveToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    batchSend(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "batchSend(uint256,tuple[],tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _ethParams: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _tokenParams: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    batchSendEth(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "batchSendEth(uint256,tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    batchSendTokens(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "batchSendTokens(uint256,tuple[],tuple[])"(
      _tollCommitment: BigNumberish,
      _params: {
        receiver: string;
        tokenAddr: string;
        amount: BigNumberish;
        pkx: BytesLike;
        ciphertext: BytesLike;
      }[],
      _transferSummary: { amount: BigNumberish; tokenAddr: string }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
